version: '3.5'

networks:
  defatul:
  inception-net:
    name: inception-net

volumes:
  wordpress_dir:
    name: wordpress_dir
    driver: local
    driver_opts:
      device: /home/amorcill/2-inception2/data/wordpress/content
      o: bind
      type: none
  mariadb_dir:
    name: mariadb_dir
    driver: local
    driver_opts:
      device: /home/amorcill/2-inception2/data/mariadb/database
      o: bind
      type: none

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_dir:/var/lib/mysql
    networks:
      - inception-net
    restart: always
    env_file: .env
  
  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-net
    restart: always
    env_file: .env
  
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception-net