version: '3.5'

networks:
  default:
  inception-net:
    name: inception-net

volumes:
  wordpress_dir:
    name: wordpress_dir
    driver: local
    driver_opts:
      device: /home/amorcill/inception/data/wordpress/content
      o: bind
      type: none
  mariadb_dir:
    name: mariadb_dir
    driver: local
    driver_opts:
      device: /home/amorcill/inception/data/mariadb/database
      o: bind
      type: none

services:
  mariadb:
    image: inception-mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_dir:/var/lib/mysql
    networks:
      - inception-net
    restart: always
    env_file: .env
  
  wordpress:
    image: inception-wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-net
    restart: always
    env_file: .env
  
  nginx:
    image: inception-nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress_dir:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception-net
  
  # adminer:
  #   image: inception-adminer
  #   container_name: adminer
  #   build: ./requirements/adminer
  #   depends_on:
  #     - mariadb
  #   restart: always
  #   networks:
  #     - inception-net
    